trigger: none

pr: none

jobs:
  - template: ".pipelines/jobs/ci.yml"
    parameters:
      BuildSolution: "$(Build.SourcesDirectory)/Activities/Community.Activities.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "Any CPU"
