parameters:
  BuildSolution: "$(Build.SourcesDirectory)/Activities/Community.Activities.sln"
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"
  VmImage: "windows-latest"
  Demands: 
  - msbuild
  - visualstudio
  - vstest

jobs:
- job: |CI_Community_Activities_${{ parameters.BuildSolution }}"
  displayName: "CI - Community Activities"

  pool:
    vmImage: ${{ parameters.VmImage }}
    demands: ${{ parameters.Demands }}

  steps:
  - template: "../steps/build.yml"
    parameters:
      BuildSolution:      ${{ parameters.BuildSolution }}
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      BuildPlatform:      ${{ parameters.BuildPlatform }}

  - template: "../steps/test.yml"
    parameters:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      BuildPlatform:      ${{ parameters.BuildPlatform }}

  - template: "../steps/package_proj.yml"
    parameters:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
