trigger: none

pr: none

jobs:
  - template: "../.pipelines/jobs/ci_proj.yml"
    parameters:
      BuildProject: "UiPath.Twilio.Activities/UiPath.Twilio.Activities.csproj"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Twilio\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
