parameters:
  BuildProject: ""
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"
  NuGetVersionSpec: "4.3.0"
  NuGetConfigPath: "$(Build.SourcesDirectory)/Activities/.nuget/NuGet.Config"
  Dependencies: []
  restoreDependencies: []
  rootPath: $(Build.SourcesDirectory)

steps:
- ${{ each depend in parameters.restoreDependencies }}:
  - task: NuGetCommand@2
    displayName: "Restore Nuget packages"
    inputs:
      restoreSolution:  ${{ format('{0}{1}', parameters.rootPath, parameters.depend) }}
      feedsToUse:       "config"
      nugetConfigPath:  ${{ parameters.NuGetConfigPath }}
      restoreDirectory: ${{ parameters.rootPath }}packages/
  # - task: VSBuild@1
  #   displayName: "Build Solution"
  #   inputs:
  #     solution:       $(Build.SourcesDirectory)/${{ depend }}
  #     platform:       ${{ parameters.BuildPlatform }}
  #     configuration:  ${{ parameters.BuildConfiguration }}

- task: NuGetCommand@2
  displayName: "Restore Nuget packages"
  inputs:
    restoreSolution:  ${{ format('{0}{1}', parameters.rootPath, parameters.BuildProject) }}
    feedsToUse:       "config"
    nugetConfigPath:  ${{ parameters.NuGetConfigPath }}
    restoreDirectory: ${{ parameters.rootPath }}packages/
- task: VSBuild@1
  displayName: "Build Solution"
  inputs:
    solution:       ${{ format('{0}{1}', parameters.rootPath, parameters.BuildProject) }}
    platform:       ${{ parameters.BuildPlatform }}
    configuration:  ${{ parameters.BuildConfiguration }}
