parameters:
  BuildSolution: "$(Build.SourcesDirectory)/Activities/Community.Activities.sln"
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"
  NuGetVersionSpec: "4.3.0"
  NuGetConfigPath: "$(Build.SourcesDirectory)/Activities/.nuget/NuGet.Config"

steps:
- task: NuGetCommand@2
  displayName: "Restore Nuget packages"
  inputs:
    restoreSolution:  ${{ parameters.BuildSolution }}
    feedsToUse:       "config"
    nugetConfigPath:  ${{ parameters.NuGetConfigPath }}

- task: VSBuild@1
  displayName: "Build Solution"
  inputs:
    solution:       ${{ parameters.BuildSolution }}
    platform:       ${{ parameters.BuildPlatform }}
    configuration:  ${{ parameters.BuildConfiguration }}
